version: "3.8"

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - backend_node_modules:/app/node_modules
    networks:
      - backend_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - frontend_node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - frontend_network
      - backend_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
        reservations:
          cpus: "0.25"
          memory: "512M"

volumes:
  backend_node_modules:
  frontend_node_modules:

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
